server {
    listen 80;
    server_name localhost;
    
    # Увеличиваем лимит загрузки файлов (например, до 1000 МБ)
    client_max_body_size 1000M;

    # Раздача статического фронтенда (Vite build)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Проксирование всех запросов /api на бэкенд Go
    # ВАЖНО: Вместо localhost:8000 мы пишем имя сервиса из docker-compose (app)
    # и внутренний порт, на котором слушает Go (берется из переменной SERVER_PORT / GO_SERVER_PORT)
    location /api/ {
        proxy_pass http://app:8000/api/; # Убедитесь, что порт совпадает с внутренним портом контейнера app
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}